[package]
name = "to-do-app"
version = "0.1.0"
authors = ["Arda Cetinkaya"]
edition = "2018"

[dependencies]
structopt = "0.3"
serde_json = "1.0"
home = "0.5"

[dependencies.serde] 
version = "1.0"
features = ["derive"] 

[dependencies.chrono]
version = "0.4"
features = ["serde"] 